<a href="https://colab.research.google.com/github/AnilKumarWorkhard/AITHAPAR/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#question 1 (Reverse the NumPy array:)
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
answer = np.flip(arr)
print("final array ",answer)

final array  [5 4 6 3 2 1]


In [ ]:
#question 2 (Flatten the NumPy array:)
import numpy as np

arr = np.array([[1,2,3], [2,4,5],[1,2,3]])

answer = arr.flatten()

print( answer )

[1 2 3 2 4 5 1 2 3]


In [ ]:
#question 3 (Compare the numpy arrays:)
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
print(array1 == array2)


[[ True  True]
 [ True  True]]


In [ ]:
#question 4 (Find the most frequent value and their indice(s) in the following arrays:

import numpy as np
from collections import Counter

def most_frequent_value(arr):
    # Count the frequency of each element in the array
    freq = Counter(arr)

    # Find the most frequent value
    most_frequent = freq.most_common(1)[0][0]

    # Find the indices of the most frequent value
    indices = np.where(arr == most_frequent)[0]

    return most_frequent, indices

# Arrays
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Finding the most frequent value and indices for x
most_frequent_x, indices_x = most_frequent_value(x)
print(f"Array x: Most frequent value is {most_frequent_x} at indices {indices_x}")

# Finding the most frequent value and indices for y
most_frequent_y, indices_y = most_frequent_value(y)
print(f"Array y: Most frequent value is {most_frequent_y} at indices {indices_y}")


Array x: Most frequent value is 1 at indices [0 5 7 8 9]
Array y: Most frequent value is 1 at indices [0 1 2]


In [ ]:
#question 5
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
answer = gfg.sum()

# ii. Sum of all elements row-wise
row_sum = np.sum(gfg, axis=1)

# iii. Sum of all elements column-wise
col_sum = np.sum(gfg, axis=0)

print(answer)
print(row_sum)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
#question 6
import numpy as np

# Define the matrix
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i. Sum of diagonal elements
sum_diagonal = np.trace(n_array)

# ii. Eigenvalues of matrix
eigen_values = np.linalg.eigvals(n_array)

# iii. Eigenvectors of matrix
eigen_values, eigen_vectors = np.linalg.eig(n_array)

# iv. Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)

# v. Determinant of matrix
determinant = np.linalg.det(n_array)

# Output results
print(f"Sum of diagonal elements: {sum_diagonal}")
print(f"Eigenvalues of matrix: {eigen_values}")
print(f"Eigenvectors of matrix:\n{eigen_vectors}")
print(f"Inverse of matrix:\n{inverse_matrix}")
print(f"Determinant of matrix: {determinant}")

Sum of diagonal elements: 176
Eigenvalues of matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of matrix:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [ ]:
#question 7
import numpy as np

# Case i
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

# Matrix multiplication
product1 = np.dot(p1, q1)

# Flatten the matrices and find covariance
covariance1 = np.cov(p1.flatten(), q1.flatten())

# Case ii
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product2 = np.dot(p2, q2)

# Flatten the matrices and find covariance
covariance2 = np.cov(p2.flatten(), q2.flatten())

# Output results
print("Case i:")
print(f"Matrix multiplication result:\n{product1}")
print(f"Covariance between matrices:\n{covariance1}\n")

print("Case ii:")
print(f"Matrix multiplication result:\n{product2}")
print(f"Covariance between matrices:\n{covariance2}")


Case i:
Matrix multiplication result:
[[16 19]
 [26 31]]
Covariance between matrices:
[[0.66666667 1.        ]
 [1.         1.66666667]]

Case ii:
Matrix multiplication result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between matrices:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
#question 8
import numpy as np
from itertools import product

# Define the matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# i. Inner product
inner_product = np.inner(x, y)

# ii. Outer product
outer_product = np.outer(x, y)

# iii. Cartesian product
cartesian_product = np.array(list(product(x.flatten(), y.flatten())))
print(f"Inner product:\n{inner_product}\n")
print(f"Outer product:\n{outer_product}\n")
print(f"Cartesian product:\n{cartesian_product}")


Inner product:
[[17 52]
 [13 62]]

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
#Q2: Based on NumPy Mathematics and Statistics

In [ ]:
# (A)
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)

# ii. Find the 25th, 50th, and 75th percentile
# For flattened array
percentiles_flattened = np.percentile(array.flatten(), [25, 50, 75])

# For each column
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)

# For each row
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

# iii. Mean, Median, and Standard Deviation
# For flattened array
mean_flattened = np.mean(array.flatten())
median_flattened = np.median(array.flatten())
std_flattened = np.std(array.flatten())

# For each column
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

# For each row
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print(f"i. Element-wise absolute value:\n{abs_array}\n")

print(f"ii. Percentiles of the flattened array (25th, 50th, 75th): {percentiles_flattened}")
print(f"Percentiles of each column:\n{percentiles_columns}")
print(f"Percentiles of each row:\n{percentiles_rows}\n")

print(f"iii. Flattened array: Mean = {mean_flattened}, Median = {median_flattened}, Std Dev = {std_flattened}")
print(f"Columns: Mean = {mean_columns}, Median = {median_columns}, Std Dev = {std_columns}")
print(f"Rows: Mean = {mean_rows}, Median = {median_rows}, Std Dev = {std_rows}")


i. Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

ii. Percentiles of the flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]
Percentiles of each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles of each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

iii. Flattened array: Mean = -0.5, Median = -0.5, Std Dev = 3.8622100754188224
Columns: Mean = [-1.5  1.5 -1.5], Median = [-1.5  1.5 -1.5], Std Dev = [2.5 3.5 4.5]
Rows: Mean = [ 0.66666667 -1.66666667], Median = [ 1. -4.], Std Dev = [2.05480467 4.78423336]


In [ ]:
#(b)
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor values
floor_values = np.floor(a)

# Ceiling values
ceiling_values = np.ceil(a)

# Truncated values (truncate towards zero)
truncated_values = np.trunc(a)

# Rounded values
rounded_values = np.round(a)
print(f"Original array: {a}\n")
print(f"Floor values: {floor_values}")
print(f"Ceiling values: {ceiling_values}")
print(f"Truncated values: {truncated_values}")
print(f"Rounded values: {rounded_values}")


Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#Q3: Based on Searching and Sorting

In [ ]:
#(a)
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of the sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_elements = np.sort(array)[:4]

# iv. 5 largest elements
largest_elements = np.sort(array)[-5:]
print(f"Original array: {array}\n")
print(f"Sorted array: {sorted_array}")
print(f"Indices of sorted array: {sorted_indices}")
print(f"4 smallest elements: {smallest_elements}")
print(f"5 largest elements: {largest_elements}")


Original array: [ 10  52  62  16  16  54 453]

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [ ]:
#(b)
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only (where the element is equal to its integer representation)
integer_elements = array[array == array.astype(int)]

# ii. Float elements only (where the element is not equal to its integer representation)
float_elements = array[array != array.astype(int)]
print(f"Original array: {array}\n")
print(f"Integer elements only: {integer_elements}")
print(f"Float elements only: {float_elements}")


Original array: [1.  1.2 2.2 2.  3.  2. ]

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]
